"""empty message

Revision ID: 36edb5043bee
Revises: fc73ed78f275
Create Date: 2024-01-16 20:34:06.038438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '36edb5043bee'
down_revision: Union[str, None] = 'fc73ed78f275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailydramarank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rankdate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('naver', sa.JSON(), nullable=True),
    sa.Column('fundex', sa.JSON(), nullable=True),
    sa.Column('jw', sa.JSON(), nullable=True),
    sa.Column('Wavve', sa.JSON(), nullable=True),
    sa.Column('KMDB', sa.JSON(), nullable=True),
    sa.Column('IMDB', sa.JSON(), nullable=True),
    sa.Column('TMDB', sa.JSON(), nullable=True),
    sa.Column('Watcha', sa.JSON(), nullable=True),
    sa.Column('Netflix', sa.JSON(), nullable=True),
    sa.Column('Tving', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rankdate')
    )
    op.create_table('dailyottrank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rankdate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('naver', sa.JSON(), nullable=True),
    sa.Column('fundex', sa.JSON(), nullable=True),
    sa.Column('jw', sa.JSON(), nullable=True),
    sa.Column('Wavve', sa.JSON(), nullable=True),
    sa.Column('KMDB', sa.JSON(), nullable=True),
    sa.Column('IMDB', sa.JSON(), nullable=True),
    sa.Column('TMDB', sa.JSON(), nullable=True),
    sa.Column('Watcha', sa.JSON(), nullable=True),
    sa.Column('Netflix', sa.JSON(), nullable=True),
    sa.Column('Tving', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rankdate')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailyottrank')
    op.drop_table('dailydramarank')
    # ### end Alembic commands ###
