"""empty message

Revision ID: de0caaa45727
Revises: 36edb5043bee
Create Date: 2024-01-17 09:38:05.890177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'de0caaa45727'
down_revision: Union[str, None] = '36edb5043bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailyottrank', 'KMDB')
    op.drop_column('dailyottrank', 'Watcha')
    op.drop_column('dailyottrank', 'IMDB')
    op.drop_column('dailyottrank', 'Wavve')
    op.drop_column('dailyottrank', 'TMDB')
    op.drop_column('dailyottrank', 'Netflix')
    op.drop_column('dailyottrank', 'Tving')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailyottrank', sa.Column('Tving', sqlite.JSON(), nullable=True))
    op.add_column('dailyottrank', sa.Column('Netflix', sqlite.JSON(), nullable=True))
    op.add_column('dailyottrank', sa.Column('TMDB', sqlite.JSON(), nullable=True))
    op.add_column('dailyottrank', sa.Column('Wavve', sqlite.JSON(), nullable=True))
    op.add_column('dailyottrank', sa.Column('IMDB', sqlite.JSON(), nullable=True))
    op.add_column('dailyottrank', sa.Column('Watcha', sqlite.JSON(), nullable=True))
    op.add_column('dailyottrank', sa.Column('KMDB', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
